@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to preparing a command line for running
@REM the cspybat command line utility using the appropriate settings.
@REM
@REM Note that this file is generated every time a new debug session
@REM is initialized, so you may want to move or rename the file before
@REM making changes.
@REM
@REM You can launch cspybat by typing the name of this batch file followed
@REM by the name of the debug file (usually an ELF/DWARF or UBROF file).
@REM
@REM Read about available command line parameters in the C-SPY Debugging
@REM Guide. Hints about additional command line parameters that may be
@REM useful in specific cases:
@REM   --download_only   Downloads a code image without starting a debug
@REM                     session afterwards.
@REM   --silent          Omits the sign-on message.
@REM   --timeout         Limits the maximum allowed execution time.
@REM 


@echo off 

if not "%~1" == "" goto debugFile 

@echo on 

"C:\Program Files (x86)\IAR Systems\Embedded Workbench 7.5\common\bin\cspybat" -f "D:\智能车\逐飞科技\总钻风摄像头\总钻风例程(V2版本)\K60例程\1.一幅图像采集完成触发中断\总钻风例程K60(上位机显示灰度图像) - 副本\Projecct\IAR\program\settings\SeekFree_Kinetis.MK60DN_Debug.general.xcl" --backend -f "D:\智能车\逐飞科技\总钻风摄像头\总钻风例程(V2版本)\K60例程\1.一幅图像采集完成触发中断\总钻风例程K60(上位机显示灰度图像) - 副本\Projecct\IAR\program\settings\SeekFree_Kinetis.MK60DN_Debug.driver.xcl" 

@echo off 
goto end 

:debugFile 

@echo on 

"C:\Program Files (x86)\IAR Systems\Embedded Workbench 7.5\common\bin\cspybat" -f "D:\智能车\逐飞科技\总钻风摄像头\总钻风例程(V2版本)\K60例程\1.一幅图像采集完成触发中断\总钻风例程K60(上位机显示灰度图像) - 副本\Projecct\IAR\program\settings\SeekFree_Kinetis.MK60DN_Debug.general.xcl" "--debug_file=%~1" --backend -f "D:\智能车\逐飞科技\总钻风摄像头\总钻风例程(V2版本)\K60例程\1.一幅图像采集完成触发中断\总钻风例程K60(上位机显示灰度图像) - 副本\Projecct\IAR\program\settings\SeekFree_Kinetis.MK60DN_Debug.driver.xcl" 

@echo off 
:end